/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CImport } from './routes/c'
import { Route as CChatIDImport } from './routes/c/$chatID'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CRoute = CImport.update({
  path: '/c',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CChatIDRoute = CChatIDImport.update({
  path: '/$chatID',
  getParentRoute: () => CRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/c': {
      id: '/c'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CImport
      parentRoute: typeof rootRoute
    }
    '/c/$chatID': {
      id: '/c/$chatID'
      path: '/$chatID'
      fullPath: '/c/$chatID'
      preLoaderRoute: typeof CChatIDImport
      parentRoute: typeof CImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CRoute: CRoute.addChildren({ CChatIDRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/c"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/c": {
      "filePath": "c.tsx",
      "children": [
        "/c/$chatID"
      ]
    },
    "/c/$chatID": {
      "filePath": "c/$chatID.tsx",
      "parent": "/c"
    }
  }
}
ROUTE_MANIFEST_END */
