CREATE TABLE Chat (
    id TEXT NOT NULL PRIMARY KEY,
    userID TEXT NOT NULL,
    previewName TEXT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ChatMessage (
    id TEXT NOT NULL PRIMARY KEY,
    userID TEXT NOT NULL,
    chatID TEXT NOT NULL,
    messageType TEXT NOT NULL,
    messageContent TEXT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chatID) REFERENCES Chat(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX ChatMessage_chatID_idx ON ChatMessage(chatID);

CREATE TABLE ReplicacheClientGroup (
    id TEXT NOT NULL PRIMARY KEY,
    userID TEXT NOT NULL,
    cvrVersion INTEGER NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ReplicacheClient (
    id TEXT NOT NULL PRIMARY KEY,
    clientGroupID TEXT NOT NULL,
    lastMutationID INTEGER NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
